### ISSUE TITLE
Commented line of code

### ISSUE THREAD

**Issue by jabichris** [sz16900/newsweek-clone#1]
Good work @sz16900. unfortunately, If the color needs to be changed, don't forget to uncomment it.

<img width="717" alt="Screen Shot 2020-01-07 at 16 14 37" src="https://user-images.githubusercontent.com/33568373/71901775-49573300-3169-11ea-83c1-87b45edd5f93.png">

**Comment by sz16900** [comment]
Its taken care of. Thanks

**Comment by kirokoNjenga** [comment]
Add comments on your code 
use semantic tags
